import logging
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

import pandas as pd

from robottraderslab._core import OHLCVProviderProtocol
from robottraderslab.analyser import Analyser
from robottraderslab.bootstrap import BotConfig, ReportConfig
from robottraderslab.exchanges import Balance, Currency

from .simulator import EquitySnapshot

logger = logging.getLogger(__name__)


@dataclass(frozen=True, slots=True)
class BacktestOutputs:
    """What a backtest produced: closing balances, equity over time, and fills.

    The accessors turn those into the curves and the analyser a report is
    built from.
    """

    final_balance: dict[Currency, float]
    equity_currency: Currency
    daily_equity_snapshots: list[EquitySnapshot]
    trade_equity_snapshots: list[EquitySnapshot]
    fills: pd.DataFrame
    ohlcv_provider: OHLCVProviderProtocol
    bot_config: BotConfig | None = None
    config_dir: Path | None = None

    def create_analyser(self, save: bool = True) -> Analyser:
        """Build the analyser the performance report and the figures are
        read from.

        Args:
            save: Write the run's folder under `reports/` beside the
                configuration file: its configuration, its performance
                report and one page drawing every configured market.
                `plot_candlesticks` then opens the saved page without
                rendering a new one.

        Raises:
            RuntimeError: If the run closed no trade, so there is nothing to
                analyse.
        """
        analyser = Analyser.from_fills(
            self.fills,
            self.get_equity_curve(),
            self.ohlcv_provider,
            report_config=self._report_config(),
            profiles=self._configured_profiles(),
        )
        if analyser.closed_trades_count == 0:
            raise RuntimeError(
                "No trades generated by the backtest, aborting analysis."
            )

        if (
            save
            and self.bot_config is not None
            and self.bot_config.config_file is not None
        ):
            directory = analyser.save_run(
                self.bot_config, self.bot_config.strategy.strategy_class
            )
            logger.info("Run saved to %s", directory)

        return analyser

    def get_balance_curves(
        self, source: Literal["daily", "trade"] = "daily"
    ) -> pd.DataFrame:
        """Follow each currency's balance across the run.

        Args:
            source: "daily" for midnight snapshots, "trade" for trade-time ones.

        Returns:
            Balance by timestamp, one column per currency.
        """
        snapshots = (
            self.daily_equity_snapshots
            if source == "daily"
            else self.trade_equity_snapshots
        )

        if not snapshots:
            return pd.DataFrame()

        all_currencies: set[Currency] = set()
        for snapshot in snapshots:
            all_currencies.update(snapshot.balances.keys())

        balance_data: dict[Currency, list[float]] = {}
        timestamps = []

        default_balance = Balance(locked=0.0, total=0.0)
        for snapshot in snapshots:
            timestamps.append(snapshot.timestamp)
            for currency in all_currencies:
                balance_data.setdefault(currency, []).append(
                    snapshot.balances.get(currency, default_balance).total
                )

        df = pd.DataFrame(balance_data, index=timestamps)
        df.index.name = "timestamp"
        return df

    def get_equity_curve(
        self,
        currency: Currency | None = None,
        source: Literal["daily", "trade"] = "daily",
    ) -> pd.Series:
        """Value the portfolio at each recorded snapshot.

        Args:
            currency: Currency to value the portfolio in, defaulting to the one
                the run settled in.
            source: "daily" for midnight snapshots, "trade" for trade-time ones.

        Returns:
            Equity by timestamp.
        """
        snapshots = (
            self.daily_equity_snapshots
            if source == "daily"
            else self.trade_equity_snapshots
        )

        if not snapshots:
            return pd.Series(dtype=float)

        return pd.Series(
            {
                snapshot.timestamp: snapshot.get_equity(
                    currency or self.equity_currency
                )
                for snapshot in snapshots
            }
        )

    def _configured_profiles(self) -> Sequence[dict[str, Any]]:
        if self.bot_config is None:
            return []
        return self.bot_config.strategy.profiles

    def _report_config(self) -> ReportConfig:
        if self.bot_config is None:
            return ReportConfig()
        return self.bot_config.report
